name: Deploy to Cloudflare Workers
on:
  workflow_dispatch:
    branches: 
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sed -i -e "s/CF_ACCOUNT_ID/${{ secrets.CF_ACCOUNT_ID }}/" wrangler.toml
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            FX_CLIENT_ID
            FX_CLIENT_SECRET
            FX_REFRESH_TOKEN
        env:
          FX_CLIENT_ID: ${{ secrets.FX_CLIENT_ID }}
          FX_CLIENT_SECRET: ${{ secrets.FX_CLIENT_SECRET }}
          FX_REFRESH_TOKEN: ${{ secrets.FX_REFRESH_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
